project_name: gowrap
before:
  hooks:
    - make test
builds:
- 
  main: ./cmd/gowrap/
  binary: gowrap
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows

  ldflags:
    - -X main.version={{.Version}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
